- name: Configure system tooling
  hosts: all
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
    - name: Install basic tooling
      apt:
        name:
          - curl
          - bzip2
        state: present
        update_cache: yes
