---
- name: Install Anaconda/Miniconda
  hosts: all
  become: yes
  vars:
    conda_installer_url: "https://pro.anaconda.com/miniconda/Miniconda3-latest-Linux-aarch64.sh"
    conda_installer_path: "/tmp/miniconda-installer.sh"
    conda_install_dir: "/opt/anaconda"
    conda_user: "{{ ansible_user }}"
  tasks:
    - name: Download Miniconda installer
      get_url:
        url: "{{ conda_installer_url }}"
        dest: "{{ conda_installer_path }}"
        mode: '0550'
    - name: Create Conda installation directory
      file:
        path: "{{ conda_install_dir }}"
        state: directory
        owner: "{{ conda_user }}"
        mode: '0755'
        recurse: yes
    - name: Run Miniconda installer in batch mode
      shell: "{{ conda_installer_path }} -b -u -p {{ conda_install_dir }}"
      args:
        creates: "{{ conda_install_dir }}/bin/conda"
    - name: Remove installer script
